### ISSUE TITLE
Blank page rendered on Google Chrome

### ISSUE THREAD

**Issue by Vdragon** [g0v/color#2]
![_042](https://cloud.githubusercontent.com/assets/1192163/8395957/479bef02-1dc2-11e5-94d4-4132d120ee42.png)
![_043](https://cloud.githubusercontent.com/assets/1192163/8395958/55a4b87c-1dc2-11e5-9231-15d45c452c5c.png)

**Comment by yutin1987** [comment]
please try again, thanks.

**Comment by Vdragon** [comment]
有畫面了，感謝
