### ISSUE TITLE
無法get 2個以上的json data

### ISSUE THREAD

**Issue by yutin1987** [g0v/color#6]
錯誤發生環境，只在iPhone內建的瀏覽器

//tonyq.org/kptaipei/api-20150628.php
//raw.githubusercontent.com/harry2690/psof/gh-pages/hotels.json
//raw.githubusercontent.com/g0v/blood/gh-pages/blood.json

目前只有 //tonyq.org/kptaipei/api-20150628.php 被順利get

**Comment by yutin1987** [comment]
fixed.
改
//harry2690.github.io/psof/hotels.json 和 //g0v.github.io/blood/blood.json
可能會多 cache 個五分鐘

**Comment by LeeChSien** [comment]
這是 CORS 的問題吧，同 domain 就可以了
